kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
  labels:
    app: blockchain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "ceph-storageclass-c3-cc"
