# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: shared-pv
#   labels:
#     type: local
#     name: sharedvolume
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/tmp"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  storageClassName: ceph-storageclass-c3-cc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
