# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: docker-pv
#   labels:
#     type: local
#     name: dockervolume
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/tmp-docker-pv"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-pvc
spec:
  storageClassName: ceph-storageclass-c3-cc
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi